import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.scss";
import Header from "@/comonents/Header/Header";
import { CiShoppingBasket } from "react-icons/ci";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});
export const metadata: Metadata = {
  title: "Магазин специй",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinks = [
    { id: 1, name: "Каталог", path: "/catalog" },
    { id: 2, name: "О нас", path: "#about" },
    { id: 4, name: <CiShoppingBasket className="text-2xl" />, path: "/auth" },
  ];

  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header navItems={navLinks} />
        {children}
      </body>
    </html>
  );
}
