import type { Metadata } from "next";
import Header from "@/comonents/Header/Header";

export const metadata: Metadata = {
  title: "Магазин специй",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}

AdminLayout.layout = false;
